# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4')], max_length=2)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('executed', 'Executed'), ('rolled-back', 'Rolled back'), ('failed', 'Failed'), ('vetoed', 'Vetoed')], default='proposed', max_length=15)),
                ('blast_radius', models.FloatField(default=0.0)),
                ('time_label', models.CharField(max_length=60)),
                ('rollback_plan', models.CharField(max_length=300)),
                ('policy_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_rollback_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.incident')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-external_id'],
                'unique_together': {('tenant', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='AutonomyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.tenant')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('tenant', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=40)),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4')], max_length=2)),
                ('crown_jewel_override', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4')], max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='actions.autonomypolicy')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('policy', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='ProvenanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('step', models.CharField(max_length=120)),
                ('detail', models.TextField()),
                ('ok', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace', to='actions.action')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('action', 'order')},
            },
        ),
    ]
