# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=60)),
                ('when_label', models.CharField(max_length=40)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_exports', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_external_id', models.CharField(max_length=20)),
                ('lang', models.CharField(max_length=5)),
                ('technical', models.TextField()),
                ('founder', models.TextField()),
                ('impact', models.JSONField(default=list)),
                ('decision', models.CharField(max_length=300)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'incident_external_id', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='PurpleScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('last_run_label', models.CharField(max_length=60)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='scheduled', max_length=10)),
                ('detection_label', models.CharField(default='—', max_length=20)),
                ('containment_label', models.CharField(default='—', max_length=20)),
                ('detection_seconds', models.IntegerField(blank=True, null=True)),
                ('containment_seconds', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purple_scenarios', to='core.tenant')),
            ],
            options={
                'ordering': ['external_id'],
                'unique_together': {('tenant', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ReadinessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_scores', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('tenant', 'week_label')},
            },
        ),
    ]
