# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('node_type', models.CharField(choices=[('user', 'User'), ('service', 'Service account'), ('apikey', 'API key'), ('device', 'Device'), ('cloud', 'Cloud resource'), ('repo', 'Repo'), ('saas', 'SaaS app'), ('data', 'Data asset')], max_length=10)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('crown-jewel', 'Crown Jewel')], default='medium', max_length=12)),
                ('compromised', models.BooleanField(default=False)),
                ('meta', models.CharField(blank=True, default='', max_length=200)),
                ('risk_score', models.FloatField(default=0.0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_nodes', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='OntologyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=40)),
                ('attack', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_edges', to='core.tenant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='ontology.ontologynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='ontology.ontologynode')),
            ],
            options={
                'unique_together': {('tenant', 'external_id')},
            },
        ),
    ]
