# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('trend', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_risks', to='core.tenant')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('tenant', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(max_length=20)),
                ('org_score', models.IntegerField(blank=True, null=True)),
                ('forecast', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('tenant', 'day_label')},
            },
        ),
    ]
