# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('available', 'Available'), ('connected', 'Connected'), ('error', 'Error')], default='available', max_length=12)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'connector_id')},
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=60)),
                ('principal', models.CharField(max_length=200)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('geo', models.CharField(blank=True, default='', max_length=60)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('is_attack', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='core.tenant')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='connectors__tenant__da7b93_idx')],
            },
        ),
    ]
