"""
Narrative retrieval — serves stored narratives or falls back to the LLM
pipeline, then to the demo fixture. Called by IncidentNarrativeView.
"""

from reports.demo_narratives import NARRATIVE as FIXTURE

VALID_LANGS = {"en", "hi", "gu"}


def get_narrative(tenant, incident_id: str, lang: str):
    if lang not in VALID_LANGS:
        return None

    # 1. Try stored narrative (generated by the LLM pipeline)
    from reports.models import IncidentNarrative

    stored = IncidentNarrative.objects.filter(
        tenant=tenant, incident_external_id=incident_id, lang=lang
    ).first()
    if stored:
        return {
            "technical": stored.technical,
            "founder": stored.founder,
            "impact": stored.impact,
            "decision": stored.decision,
        }

    # 2. For INC-042 fall back to the rich fixture (EN/HI/GU already there)
    if incident_id == "INC-042" and lang in FIXTURE:
        return FIXTURE[lang]

    # 3. Generate on-demand for other incidents (EN only; HI/GU via IndicTrans2)
    if lang == "en":
        return _generate_and_store(tenant, incident_id, lang)

    # 4. For HI/GU with no stored narrative, return EN fixture translated stub
    return FIXTURE.get("en")


def _generate_and_store(tenant, incident_id: str, lang: str):
    from core.models import Incident
    from reports.llm import generate_narrative
    from reports.models import IncidentNarrative

    incident = Incident.objects.filter(tenant=tenant, external_id=incident_id).first()
    if incident is None:
        return None

    narrative = generate_narrative(
        tenant, incident,
        incident.attack_steps.all(),
        [],  # provenance steps — empty for on-demand generation
    )
    IncidentNarrative.objects.update_or_create(
        tenant=tenant, incident_external_id=incident_id, lang=lang,
        defaults={
            "technical": narrative["technical"],
            "founder": narrative["founder"],
            "impact": narrative["impact"],
            "decision": narrative["decision"],
        },
    )
    return narrative
