# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('entity', models.CharField(max_length=200)),
                ('time_label', models.CharField(max_length=60)),
                ('occurred_at', models.DateTimeField()),
                ('mitre', models.JSONField(default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('llm_provider', models.CharField(choices=[('groq', 'Groq'), ('ollama', 'Ollama')], default='groq', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('external_id', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=60)),
                ('source', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='core.incident')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='FeedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(max_length=20)),
                ('agent', models.CharField(max_length=40)),
                ('line', models.CharField(max_length=300)),
                ('tone', models.CharField(default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_lines', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=60)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('time_label', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('mitre', models.CharField(max_length=20)),
                ('mitre_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_steps', to='core.incident')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('incident', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Analyst', 'Analyst'), ('Viewer', 'Viewer')], default='Viewer', max_length=10)),
                ('display_name', models.CharField(max_length=120)),
                ('last_label', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('tenant', 'external_id')},
        ),
        migrations.CreateModel(
            name='AgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('status', models.CharField(default='idle', max_length=30)),
                ('current_task', models.CharField(blank=True, default='', max_length=200)),
                ('stat', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_states', to='core.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tenant', 'agent_id')},
            },
        ),
    ]
